// react-fe/src/pages/app/AppChatPage.tsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router'
import { toast } from 'sonner'
import {
  Info,
  Download,
  CloudUpload,
  Send,
  ExternalLink,
  Edit,
  Loader2,
  X,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Alert, AlertDescription } from '@/components/ui/alert'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import MarkdownRenderer from '@/components/MarkdownRenderer'
import AppDetailModal from '@/components/AppDetailModal'
import DeploySuccessModal from '@/components/DeploySuccessModal'
import { useUserStore } from '@/stores/userStore'
import {
  getAppVoById,
  deployApp as deployAppApi,
  deleteApp as deleteAppApi,
} from '@/api/appController'
import { listAppChatHistory } from '@/api/chatHistoryController'
import { CodeGenTypeEnum, formatCodeGenType } from '@/utils/codeGenTypes'
import { API_BASE_URL, getStaticPreviewUrl } from '@/config/env'
import { VisualEditor, type ElementInfo } from '@/utils/visualEditor'
import request from '@/request'
import aiAvatarImg from '@/assets/aiAvatar.png'

interface Message {
  type: 'user' | 'ai'
  content: string
  loading?: boolean
  createTime?: string
}

export default function AppChatPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { loginUser } = useUserStore()

  // App info
  const [appInfo, setAppInfo] = useState<API.AppVO>()
  const appId = id

  // Chat related
  const [messages, setMessages] = useState<Message[]>([])
  const [userInput, setUserInput] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const messagesContainerRef = useRef<HTMLDivElement>(null)

  // Chat history related
  const [loadingHistory, setLoadingHistory] = useState(false)
  const [hasMoreHistory, setHasMoreHistory] = useState(false)
  const [lastCreateTime, setLastCreateTime] = useState<string>()

  // Preview related
  const [previewUrl, setPreviewUrl] = useState('')

  // Deploy related
  const [deploying, setDeploying] = useState(false)
  const [deployModalVisible, setDeployModalVisible] = useState(false)
  const [deployUrl, setDeployUrl] = useState('')

  // Download related
  const [downloading, setDownloading] = useState(false)

  // Visual editing related
  const [isEditMode, setIsEditMode] = useState(false)
  const [selectedElementInfo, setSelectedElementInfo] = useState<ElementInfo | null>(null)
  const visualEditorRef = useRef<VisualEditor | null>(null)

  // App detail modal
  const [appDetailVisible, setAppDetailVisible] = useState(false)

  // Permissions
  const isOwner = appInfo?.userId === loginUser.id
  const isAdmin = loginUser.userRole === 'admin'

  // Initialize visual editor
  useEffect(() => {
    visualEditorRef.current = new VisualEditor({
      onElementSelected: (elementInfo: ElementInfo) => {
        setSelectedElementInfo(elementInfo)
      },
    })

    // Listen for iframe messages
    const handleMessage = (event: MessageEvent) => {
      visualEditorRef.current?.handleIframeMessage(event)
    }
    window.addEventListener('message', handleMessage)

    return () => {
      window.removeEventListener('message', handleMessage)
    }
  }, [])

  // Scroll to bottom
  const scrollToBottom = useCallback(() => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTop = messagesContainerRef.current.scrollHeight
    }
  }, [])

  // Update preview
  const updatePreview = useCallback(() => {
    if (appId && appInfo?.codeGenType) {
      const newPreviewUrl = getStaticPreviewUrl(
        appInfo.codeGenType || CodeGenTypeEnum.HTML,
        appId
      )
      setPreviewUrl(newPreviewUrl)
    }
  }, [appId, appInfo?.codeGenType])

  // Load chat history
  const loadChatHistory = useCallback(
    async (isLoadMore = false) => {
      if (!appId || loadingHistory) return
      setLoadingHistory(true)

      try {
        const params: API.listAppChatHistoryParams = {
          appId: Number(appId),
          pageSize: 10,
        }
        if (isLoadMore && lastCreateTime) {
          params.lastCreateTime = lastCreateTime
        }

        const res = await listAppChatHistory(params)
        if (res.data.code === 0 && res.data.data) {
          const chatHistories = res.data.data.records || []
          if (chatHistories.length > 0) {
            const historyMessages: Message[] = chatHistories
              .map((chat) => ({
                type: (chat.messageType === 'user' ? 'user' : 'ai') as 'user' | 'ai',
                content: chat.message || '',
                createTime: chat.createTime,
              }))
              .reverse()

            if (isLoadMore) {
              setMessages((prev) => [...historyMessages, ...prev])
            } else {
              setMessages(historyMessages)
            }
            setLastCreateTime(chatHistories[chatHistories.length - 1]?.createTime)
            setHasMoreHistory(chatHistories.length === 10)
          } else {
            setHasMoreHistory(false)
          }
        }
      } catch (error) {
        console.error('Failed to load chat history:', error)
        toast.error('Failed to load chat history')
      } finally {
        setLoadingHistory(false)
      }
    },
    [appId, loadingHistory, lastCreateTime]
  )

  // Generate code - use EventSource for streaming
  const generateCode = useCallback(
    async (userMessage: string, aiMessageIndex: number) => {
      let streamCompleted = false

      try {
        const baseURL = request.defaults.baseURL || API_BASE_URL
        const params = new URLSearchParams({
          appId: appId || '',
          message: userMessage,
        })

        const url = `${baseURL}/app/chat/gen/code?${params}`
        const eventSource = new EventSource(url, { withCredentials: true })

        let fullContent = ''

        eventSource.onmessage = (event) => {
          if (streamCompleted) return

          try {
            const parsed = JSON.parse(event.data)
            const content = parsed.d

            if (content !== undefined && content !== null) {
              fullContent += content
              setMessages((prev) => {
                const newMessages = [...prev]
                newMessages[aiMessageIndex] = {
                  ...newMessages[aiMessageIndex],
                  content: fullContent,
                  loading: false,
                }
                return newMessages
              })
              scrollToBottom()
            }
          } catch (error) {
            console.error('Failed to parse message:', error)
          }
        }

        eventSource.addEventListener('done', () => {
          if (streamCompleted) return

          streamCompleted = true
          setIsGenerating(false)
          eventSource.close()

          // Delay update preview
          setTimeout(async () => {
            const res = await getAppVoById({ id: Number(appId) })
            if (res.data.code === 0 && res.data.data) {
              setAppInfo(res.data.data)
            }
            updatePreview()
          }, 1000)
        })

        eventSource.addEventListener('business-error', (event: MessageEvent) => {
          if (streamCompleted) return

          try {
            const errorData = JSON.parse(event.data)
            const errorMessage = errorData.message || 'Error occurred during generation'
            setMessages((prev) => {
              const newMessages = [...prev]
              newMessages[aiMessageIndex] = {
                ...newMessages[aiMessageIndex],
                content: `❌ ${errorMessage}`,
                loading: false,
              }
              return newMessages
            })
            toast.error(errorMessage)

            streamCompleted = true
            setIsGenerating(false)
            eventSource.close()
          } catch (parseError) {
            console.error('Failed to parse error event:', parseError)
          }
        })

        eventSource.onerror = () => {
          if (streamCompleted || !isGenerating) return

          if (eventSource.readyState === EventSource.CONNECTING) {
            streamCompleted = true
            setIsGenerating(false)
            eventSource.close()

            setTimeout(async () => {
              const res = await getAppVoById({ id: Number(appId) })
              if (res.data.code === 0 && res.data.data) {
                setAppInfo(res.data.data)
              }
              updatePreview()
            }, 1000)
          } else {
            setMessages((prev) => {
              const newMessages = [...prev]
              newMessages[aiMessageIndex] = {
                ...newMessages[aiMessageIndex],
                content: 'Sorry, an error occurred during generation. Please try again.',
                loading: false,
              }
              return newMessages
            })
            toast.error('Generation failed, please try again')
            setIsGenerating(false)
          }
        }
      } catch (error) {
        console.error('Failed to create EventSource:', error)
        setMessages((prev) => {
          const newMessages = [...prev]
          newMessages[aiMessageIndex] = {
            ...newMessages[aiMessageIndex],
            content: 'Sorry, an error occurred during generation. Please try again.',
            loading: false,
          }
          return newMessages
        })
        toast.error('Generation failed, please try again')
        setIsGenerating(false)
      }
    },
    [appId, isGenerating, scrollToBottom, updatePreview]
  )

  // Fetch app info
  const fetchAppInfo = useCallback(async () => {
    if (!appId) {
      toast.error('App ID does not exist')
      navigate('/')
      return
    }

    try {
      const res = await getAppVoById({ id: Number(appId) })
      if (res.data.code === 0 && res.data.data) {
        setAppInfo(res.data.data)
        return res.data.data
      } else {
        toast.error('Failed to get app info')
        navigate('/')
      }
    } catch (error) {
      console.error('Failed to get app info:', error)
      toast.error('Failed to get app info')
      navigate('/')
    }
  }, [appId, navigate])

  // Initial load
  useEffect(() => {
    const initPage = async () => {
      const app = await fetchAppInfo()
      if (!app) return

      // Load chat history
      const params: API.listAppChatHistoryParams = {
        appId: Number(appId),
        pageSize: 10,
      }
      const historyRes = await listAppChatHistory(params)

      if (historyRes.data.code === 0 && historyRes.data.data) {
        const chatHistories = historyRes.data.data.records || []
        if (chatHistories.length > 0) {
          const historyMessages: Message[] = chatHistories
            .map((chat) => ({
              type: (chat.messageType === 'user' ? 'user' : 'ai') as 'user' | 'ai',
              content: chat.message || '',
              createTime: chat.createTime,
            }))
            .reverse()

          setMessages(historyMessages)
          setLastCreateTime(chatHistories[chatHistories.length - 1]?.createTime)
          setHasMoreHistory(chatHistories.length === 10)

          // If there are messages, show preview
          if (historyMessages.length >= 2 && app.codeGenType) {
            setPreviewUrl(getStaticPreviewUrl(app.codeGenType, appId!))
          }
        }
      }

      // Check if need to auto send initial prompt
      const isUserOwner = app.userId === loginUser.id
      if (
        app.initPrompt &&
        isUserOwner &&
        (!historyRes.data.data?.records || historyRes.data.data.records.length === 0)
      ) {
        // Auto send initial message
        const newMessages = [
          { type: 'user' as const, content: app.initPrompt },
          { type: 'ai' as const, content: '', loading: true },
        ]
        setMessages(newMessages)

        setIsGenerating(true)
        const baseURL = request.defaults.baseURL || API_BASE_URL
        const params = new URLSearchParams({
          appId: appId || '',
          message: app.initPrompt,
        })

        const url = `${baseURL}/app/chat/gen/code?${params}`
        const eventSource = new EventSource(url, { withCredentials: true })
        let streamCompleted = false
        let fullContent = ''

        eventSource.onmessage = (event) => {
          if (streamCompleted) return
          try {
            const parsed = JSON.parse(event.data)
            const content = parsed.d
            if (content !== undefined && content !== null) {
              fullContent += content
              setMessages([
                { type: 'user', content: app.initPrompt! },
                { type: 'ai', content: fullContent, loading: false },
              ])
            }
          } catch (error) {
            console.error('Failed to parse message:', error)
          }
        }

        eventSource.addEventListener('done', () => {
          if (streamCompleted) return
          streamCompleted = true
          setIsGenerating(false)
          eventSource.close()

          setTimeout(async () => {
            const res = await getAppVoById({ id: Number(appId) })
            if (res.data.code === 0 && res.data.data) {
              setAppInfo(res.data.data)
              if (res.data.data.codeGenType) {
                setPreviewUrl(getStaticPreviewUrl(res.data.data.codeGenType, appId!))
              }
            }
          }, 1000)
        })

        eventSource.onerror = () => {
          if (streamCompleted) return
          streamCompleted = true
          setIsGenerating(false)
          eventSource.close()
        }
      }
    }

    initPage()
  }, [appId, loginUser.id])

  // Send message
  const sendMessage = async () => {
    if (!userInput.trim() || isGenerating) return

    let message = userInput.trim()

    // If element is selected, add element info to prompt
    if (selectedElementInfo) {
      let elementContext = `\n\nSelected element info:`
      if (selectedElementInfo.pagePath) {
        elementContext += `\n- Page path: ${selectedElementInfo.pagePath}`
      }
      elementContext += `\n- Tag: ${selectedElementInfo.tagName.toLowerCase()}\n- Selector: ${selectedElementInfo.selector}`
      if (selectedElementInfo.textContent) {
        elementContext += `\n- Current content: ${selectedElementInfo.textContent.substring(0, 100)}`
      }
      message += elementContext
    }

    setUserInput('')

    const newMessages: Message[] = [
      ...messages,
      { type: 'user', content: message },
      { type: 'ai', content: '', loading: true },
    ]
    setMessages(newMessages)
    const aiMessageIndex = newMessages.length - 1

    // Clear selected element and exit edit mode
    if (selectedElementInfo) {
      clearSelectedElement()
      if (isEditMode) {
        toggleEditMode()
      }
    }

    setTimeout(scrollToBottom, 100)
    setIsGenerating(true)
    await generateCode(message, aiMessageIndex)
  }

  // Download code
  const downloadCode = async () => {
    if (!appId) {
      toast.error('App ID does not exist')
      return
    }

    setDownloading(true)
    try {
      const baseURL = request.defaults.baseURL || ''
      const url = `${baseURL}/app/download/${appId}`
      const response = await fetch(url, {
        method: 'GET',
        credentials: 'include',
      })

      if (!response.ok) {
        throw new Error(`Download failed: ${response.status}`)
      }

      const contentDisposition = response.headers.get('Content-Disposition')
      const fileName =
        contentDisposition?.match(/filename="(.+)"/)?.[1] || `app-${appId}.zip`

      const blob = await response.blob()
      const downloadUrl = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = downloadUrl
      link.download = fileName
      link.click()

      URL.revokeObjectURL(downloadUrl)
      toast.success('Code downloaded successfully')
    } catch (error) {
      console.error('Download failed:', error)
      toast.error('Download failed, please try again')
    } finally {
      setDownloading(false)
    }
  }

  // Deploy app
  const deployApp = async () => {
    if (!appId) {
      toast.error('App ID does not exist')
      return
    }

    setDeploying(true)
    try {
      const res = await deployAppApi({ appId: Number(appId) })

      if (res.data.code === 0 && res.data.data) {
        setDeployUrl(res.data.data)
        setDeployModalVisible(true)
        toast.success('Deploy successful')
      } else {
        toast.error('Deploy failed: ' + res.data.message)
      }
    } catch (error) {
      console.error('Deploy failed:', error)
      toast.error('Deploy failed, please try again')
    } finally {
      setDeploying(false)
    }
  }

  // Open preview in new tab
  const openInNewTab = () => {
    if (previewUrl) {
      window.open(previewUrl, '_blank')
    }
  }

  // Open deployed site
  const openDeployedSite = () => {
    if (deployUrl) {
      window.open(deployUrl, '_blank')
    }
  }

  // iframe load handler
  const onIframeLoad = () => {
    const iframe = document.querySelector('.preview-iframe') as HTMLIFrameElement
    if (iframe && visualEditorRef.current) {
      visualEditorRef.current.init(iframe)
      visualEditorRef.current.onIframeLoad()
    }
  }

  // Edit app
  const editApp = () => {
    if (appInfo?.id) {
      navigate(`/app/edit/${appInfo.id}`)
    }
  }

  // Delete app
  const deleteApp = async () => {
    if (!appInfo?.id) return

    try {
      const res = await deleteAppApi({ id: appInfo.id })
      if (res.data.code === 0) {
        toast.success('Delete successful')
        setAppDetailVisible(false)
        navigate('/')
      } else {
        toast.error('Delete failed: ' + res.data.message)
      }
    } catch (error) {
      console.error('Delete failed:', error)
      toast.error('Delete failed')
    }
  }

  // Toggle edit mode
  const toggleEditMode = () => {
    const iframe = document.querySelector('.preview-iframe') as HTMLIFrameElement
    if (!iframe) {
      toast.warning('Please wait for page to load')
      return
    }

    if (!visualEditorRef.current) {
      toast.warning('Please wait for page to load')
      return
    }

    const newEditMode = visualEditorRef.current.toggleEditMode()
    setIsEditMode(newEditMode)
  }

  // Clear selected element
  const clearSelectedElement = () => {
    setSelectedElementInfo(null)
    visualEditorRef.current?.clearSelection()
  }

  // Get input placeholder
  const getInputPlaceholder = () => {
    if (selectedElementInfo) {
      return `Editing ${selectedElementInfo.tagName.toLowerCase()} element, describe the changes you want...`
    }
    return 'Describe the website you want to generate, the more detailed the better'
  }

  // Handle key down
  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="h-[calc(100vh-120px)] flex flex-col p-4 bg-gray-50">
      {/* Header bar */}
      <div className="flex justify-between items-center py-3 px-4">
        <div className="flex items-center gap-3">
          <h1 className="text-lg font-semibold text-gray-900">
            {appInfo?.appName || 'Website Generator'}
          </h1>
          {appInfo?.codeGenType && (
            <Badge variant="secondary">{formatCodeGenType(appInfo.codeGenType)}</Badge>
          )}
        </div>
        <div className="flex gap-3">
          <Button variant="outline" onClick={() => setAppDetailVisible(true)}>
            <Info className="w-4 h-4 mr-2" />
            App Details
          </Button>
          <Button
            variant="outline"
            onClick={downloadCode}
            disabled={!isOwner || downloading}
          >
            {downloading ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Download className="w-4 h-4 mr-2" />
            )}
            Download Code
          </Button>
          <Button onClick={deployApp} disabled={deploying}>
            {deploying ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <CloudUpload className="w-4 h-4 mr-2" />
            )}
            Deploy
          </Button>
        </div>
      </div>

      {/* Main content area */}
      <div className="flex-1 flex gap-4 p-2 overflow-hidden">
        {/* Left chat area */}
        <div className="flex-[2] flex flex-col bg-white rounded-lg shadow overflow-hidden">
          {/* Messages container */}
          <div
            ref={messagesContainerRef}
            className="flex-1 p-4 overflow-y-auto scroll-smooth"
          >
            {/* Load more button */}
            {hasMoreHistory && (
              <div className="text-center pb-4">
                <Button
                  variant="link"
                  size="sm"
                  onClick={() => loadChatHistory(true)}
                  disabled={loadingHistory}
                >
                  {loadingHistory ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Loading...
                    </>
                  ) : (
                    'Load more history'
                  )}
                </Button>
              </div>
            )}

            {messages.map((message, index) => (
              <div key={index} className="mb-3">
                {message.type === 'user' ? (
                  <div className="flex justify-end items-start gap-2">
                    <div className="max-w-[70%] px-4 py-3 rounded-xl bg-blue-500 text-white leading-relaxed break-words">
                      {message.content}
                    </div>
                    <Avatar className="h-8 w-8 shrink-0">
                      <AvatarImage src={loginUser.userAvatar} />
                      <AvatarFallback>
                        {loginUser.userName?.charAt(0) || 'U'}
                      </AvatarFallback>
                    </Avatar>
                  </div>
                ) : (
                  <div className="flex items-start gap-2">
                    <Avatar className="h-8 w-8 shrink-0">
                      <AvatarImage src={aiAvatarImg} />
                      <AvatarFallback>AI</AvatarFallback>
                    </Avatar>
                    <div className="max-w-[70%] px-3 py-2 rounded-xl bg-gray-100 text-gray-900">
                      {message.content ? (
                        <MarkdownRenderer content={message.content} />
                      ) : null}
                      {message.loading && (
                        <div className="flex items-center gap-2 text-gray-500">
                          <Loader2 className="w-4 h-4 animate-spin" />
                          <span>AI is thinking...</span>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Selected element info */}
          {selectedElementInfo && (
            <Alert className="mx-4 mb-2">
              <AlertDescription>
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="font-mono text-sm font-semibold text-blue-600">
                        Selected: {selectedElementInfo.tagName.toLowerCase()}
                      </span>
                      {selectedElementInfo.id && (
                        <span className="text-green-600">#{selectedElementInfo.id}</span>
                      )}
                      {selectedElementInfo.className && (
                        <span className="text-yellow-600">
                          .{selectedElementInfo.className.split(' ').join('.')}
                        </span>
                      )}
                    </div>
                    <div className="text-sm text-gray-600 space-y-1">
                      {selectedElementInfo.textContent && (
                        <div>
                          Content: {selectedElementInfo.textContent.substring(0, 50)}
                          {selectedElementInfo.textContent.length > 50 ? '...' : ''}
                        </div>
                      )}
                      {selectedElementInfo.pagePath && (
                        <div>Page path: {selectedElementInfo.pagePath}</div>
                      )}
                      <div>
                        Selector:{' '}
                        <code className="font-mono bg-gray-100 px-1 py-0.5 rounded text-xs text-red-600 border">
                          {selectedElementInfo.selector}
                        </code>
                      </div>
                    </div>
                  </div>
                  <Button variant="ghost" size="icon" onClick={clearSelectedElement}>
                    <X className="w-4 h-4" />
                  </Button>
                </div>
              </AlertDescription>
            </Alert>
          )}

          {/* Input area */}
          <div className="p-4 bg-white">
            <div className="relative">
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <div>
                      <Textarea
                        value={userInput}
                        onChange={(e) => setUserInput(e.target.value)}
                        onKeyDown={handleKeyDown}
                        placeholder={getInputPlaceholder()}
                        rows={4}
                        maxLength={1000}
                        disabled={isGenerating || !isOwner}
                        className="pr-12 resize-none"
                      />
                    </div>
                  </TooltipTrigger>
                  {!isOwner && (
                    <TooltipContent>
                      <p>Cannot chat in others' works</p>
                    </TooltipContent>
                  )}
                </Tooltip>
              </TooltipProvider>
              <div className="absolute bottom-2 right-2">
                <Button
                  size="icon"
                  onClick={sendMessage}
                  disabled={isGenerating || !isOwner}
                >
                  {isGenerating ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Send className="w-4 h-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Right preview area */}
        <div className="flex-[3] flex flex-col bg-white rounded-lg shadow overflow-hidden">
          <div className="flex justify-between items-center px-4 py-3 border-b">
            <h3 className="text-base font-semibold">Generated Website Preview</h3>
            <div className="flex gap-2">
              {isOwner && previewUrl && (
                <Button
                  variant="link"
                  className={`h-auto p-0 ${isEditMode ? 'text-red-500' : ''}`}
                  onClick={toggleEditMode}
                >
                  <Edit className="w-4 h-4 mr-1" />
                  {isEditMode ? 'Exit Edit' : 'Edit Mode'}
                </Button>
              )}
              {previewUrl && (
                <Button variant="link" className="h-auto p-0" onClick={openInNewTab}>
                  <ExternalLink className="w-4 h-4 mr-1" />
                  Open in New Tab
                </Button>
              )}
            </div>
          </div>

          <div className="flex-1 relative overflow-hidden">
            {!previewUrl && !isGenerating && (
              <div className="flex flex-col items-center justify-center h-full text-gray-500">
                <div className="text-5xl mb-4">🌐</div>
                <p>Website preview will appear here after generation</p>
              </div>
            )}
            {isGenerating && !previewUrl && (
              <div className="flex flex-col items-center justify-center h-full text-gray-500">
                <Loader2 className="w-12 h-12 animate-spin mb-4" />
                <p>Generating website...</p>
              </div>
            )}
            {previewUrl && (
              <iframe
                src={previewUrl}
                className="preview-iframe w-full h-full border-none"
                onLoad={onIframeLoad}
              />
            )}
          </div>
        </div>
      </div>

      {/* App detail modal */}
      <AppDetailModal
        open={appDetailVisible}
        onOpenChange={setAppDetailVisible}
        app={appInfo}
        showActions={isOwner || isAdmin}
        onEdit={editApp}
        onDelete={deleteApp}
      />

      {/* Deploy success modal */}
      <DeploySuccessModal
        open={deployModalVisible}
        onOpenChange={setDeployModalVisible}
        deployUrl={deployUrl}
        onOpenSite={openDeployedSite}
      />
    </div>
  )
}

// yu-ai-code-mother-frontend/src/pages/app/AppChatPage.vue
<template>
  <div id="appChatPage">
    <!-- 顶部栏 -->
    <div class="header-bar">
      <div class="header-left">
        <h1 class="app-name">{{ appInfo?.appName || '网站生成器' }}</h1>
        <a-tag v-if="appInfo?.codegenType" color="blue" class="code-gen-type-tag">
          {{ formatCodeGenType(appInfo.codegenType) }}
        </a-tag>
      </div>
      <div class="header-right">
        <a-button type="default" @click="showAppDetail">
          <template #icon>
            <InfoCircleOutlined />
          </template>
          应用详情
        </a-button>
        <a-button
          type="primary"
          ghost
          @click="downloadCode"
          :loading="downloading"
          :disabled="!isOwner"
        >
          <template #icon>
            <DownloadOutlined />
          </template>
          下载代码
        </a-button>
        <a-button type="primary" @click="deployApp" :loading="deploying">
          <template #icon>
            <CloudUploadOutlined />
          </template>
          部署
        </a-button>
      </div>
    </div>

    <!-- 主要内容区域 -->
    <div class="main-content">
      <!-- 左侧对话区域 -->
      <div class="chat-section">
        <!-- 消息区域 -->
        <div class="messages-container" ref="messagesContainer">
          <!-- 加载更多按钮 -->
          <div v-if="hasMoreHistory" class="load-more-container">
            <a-button type="link" @click="loadMoreHistory" :loading="loadingHistory" size="small">
              加载更多历史消息
            </a-button>
          </div>
          <div v-for="(message, index) in messages" :key="index" class="message-item">
            <div v-if="message.type === 'user'" class="user-message">
              <div class="message-content">{{ message.content }}</div>
              <div class="message-avatar">
                <a-avatar :src="loginUserStore.loginUser.userAvatar" />
              </div>
            </div>
            <div v-else class="ai-message">
              <div class="message-avatar">
                <a-avatar :src="aiAvatar" />
              </div>
              <div class="message-content">
                <MarkdownRenderer v-if="message.content" :content="message.content" />
                <div v-if="message.loading" class="loading-indicator">
                  <a-spin size="small" />
                  <span>AI 正在思考...</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- 选中元素信息展示 -->
        <a-alert
          v-if="selectedElementInfo"
          class="selected-element-alert"
          type="info"
          closable
          @close="clearSelectedElement"
        >
          <template #message>
            <div class="selected-element-info">
              <div class="element-header">
                <span class="element-tag">
                  选中元素：{{ selectedElementInfo.tagName.toLowerCase() }}
                </span>
                <span v-if="selectedElementInfo.id" class="element-id">
                  #{{ selectedElementInfo.id }}
                </span>
                <span v-if="selectedElementInfo.className" class="element-class">
                  .{{ selectedElementInfo.className.split(' ').join('.') }}
                </span>
              </div>
              <div class="element-details">
                <div v-if="selectedElementInfo.textContent" class="element-item">
                  内容: {{ selectedElementInfo.textContent.substring(0, 50) }}
                  {{ selectedElementInfo.textContent.length > 50 ? '...' : '' }}
                </div>
                <div v-if="selectedElementInfo.pagePath" class="element-item">
                  页面路径: {{ selectedElementInfo.pagePath }}
                </div>
                <div class="element-item">
                  选择器:
                  <code class="element-selector-code">{{ selectedElementInfo.selector }}</code>
                </div>
              </div>
            </div>
          </template>
        </a-alert>

        <!-- 用户消息输入框 -->
        <div class="input-container">
          <div class="input-wrapper">
            <a-tooltip v-if="!isOwner" title="无法在别人的作品下对话哦~" placement="top">
              <a-textarea
                v-model:value="userInput"
                :placeholder="getInputPlaceholder()"
                :rows="4"
                :maxlength="1000"
                @keydown.enter.prevent="sendMessage"
                :disabled="isGenerating || !isOwner"
              />
            </a-tooltip>
            <a-textarea
              v-else
              v-model:value="userInput"
              :placeholder="getInputPlaceholder()"
              :rows="4"
              :maxlength="1000"
              @keydown.enter.prevent="sendMessage"
              :disabled="isGenerating"
            />
            <div class="input-actions">
              <a-button
                type="primary"
                @click="sendMessage"
                :loading="isGenerating"
                :disabled="!isOwner"
              >
                <template #icon>
                  <SendOutlined />
                </template>
              </a-button>
            </div>
          </div>
        </div>
      </div>
      <!-- 右侧网页展示区域 -->
      <div class="preview-section">
        <div class="preview-header">
          <h3>生成后的网页展示</h3>
          <div class="preview-actions">
            <a-button
              v-if="isOwner && previewUrl"
              type="link"
              :danger="isEditMode"
              @click="toggleEditMode"
              :class="{ 'edit-mode-active': isEditMode }"
              style="padding: 0; height: auto; margin-right: 12px"
            >
              <template #icon>
                <EditOutlined />
              </template>
              {{ isEditMode ? '退出编辑' : '编辑模式' }}
            </a-button>
            <a-button v-if="previewUrl" type="link" @click="openInNewTab">
              <template #icon>
                <ExportOutlined />
              </template>
              新窗口打开
            </a-button>
          </div>
        </div>
        <div class="preview-content">
          <div v-if="!previewUrl && !isGenerating" class="preview-placeholder">
            <div class="placeholder-icon">🌐</div>
            <p>网站文件生成完成后将在这里展示</p>
          </div>
          <div v-else-if="isGenerating" class="preview-loading">
            <a-spin size="large" />
            <p>正在生成网站...</p>
          </div>
          <iframe
            v-else
            :src="previewUrl"
            class="preview-iframe"
            frameborder="0"
            @load="onIframeLoad"
          ></iframe>
        </div>
      </div>
    </div>

    <!-- 应用详情弹窗 -->
    <AppDetailModal
      v-model:open="appDetailVisible"
      :app="appInfo"
      :show-actions="isOwner || isAdmin"
      @edit="editApp"
      @delete="deleteApp"
    />

    <!-- 部署成功弹窗 -->
    <DeploySuccessModal
      v-model:open="deployModalVisible"
      :deploy-url="deployUrl"
      @open-site="openDeployedSite"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick, onUnmounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { useLoginUserStore } from '@/stores/loginUser'
import {
  getAppVoById,
  deployApp as deployAppApi,
  deleteApp as deleteAppApi,
} from '@/api/appController'
import { listAppChatHistory } from '@/api/chatHistoryController'
import { CodeGenTypeEnum, formatCodeGenType } from '@/utils/codeGenTypes'
import request from '@/request'

import MarkdownRenderer from '@/components/MarkdownRenderer.vue'
import AppDetailModal from '@/components/AppDetailModal.vue'
import DeploySuccessModal from '@/components/DeploySuccessModal.vue'
import aiAvatar from '@/assets/aiAvatar.png'
import { API_BASE_URL, getStaticPreviewUrl } from '@/config/env'
import { VisualEditor, type ElementInfo } from '@/utils/visualEditor'

import {
  CloudUploadOutlined,
  SendOutlined,
  ExportOutlined,
  InfoCircleOutlined,
  DownloadOutlined,
  EditOutlined,
} from '@ant-design/icons-vue'

const route = useRoute()
const router = useRouter()
const loginUserStore = useLoginUserStore()

// 应用信息
const appInfo = ref<API.AppVO>()
const appId = ref<any>()

// 对话相关
interface Message {
  type: 'user' | 'ai'
  content: string
  loading?: boolean
  createTime?: string
}

const messages = ref<Message[]>([])
const userInput = ref('')
const isGenerating = ref(false)
const messagesContainer = ref<HTMLElement>()

// 对话历史相关
const loadingHistory = ref(false)
const hasMoreHistory = ref(false)
const lastCreateTime = ref<string>()
const historyLoaded = ref(false)

// 预览相关
const previewUrl = ref('')
const previewReady = ref(false)

// 部署相关
const deploying = ref(false)
const deployModalVisible = ref(false)
const deployUrl = ref('')

// 下载相关
const downloading = ref(false)

// 可视化编辑相关
const isEditMode = ref(false)
const selectedElementInfo = ref<ElementInfo | null>(null)
const visualEditor = new VisualEditor({
  onElementSelected: (elementInfo: ElementInfo) => {
    selectedElementInfo.value = elementInfo
  },
})

// 权限相关
const isOwner = computed(() => {
  return appInfo.value?.userId === loginUserStore.loginUser.id
})

const isAdmin = computed(() => {
  return loginUserStore.loginUser.userRole === 'admin'
})

// 应用详情相关
const appDetailVisible = ref(false)

// 显示应用详情
const showAppDetail = () => {
  appDetailVisible.value = true
}

// 加载对话历史
const loadChatHistory = async (isLoadMore = false) => {
  if (!appId.value || loadingHistory.value) return
  loadingHistory.value = true
  try {
    const params: API.listAppChatHistoryParams = {
      appId: appId.value,
      pageSize: 10,
    }
    // 如果是加载更多，传递最后一条消息的创建时间作为游标
    if (isLoadMore && lastCreateTime.value) {
      params.lastCreateTime = lastCreateTime.value
    }
    const res = await listAppChatHistory(params)
    if (res.data.code === 0 && res.data.data) {
      const chatHistories = res.data.data.records || []
      if (chatHistories.length > 0) {
        // 将对话历史转换为消息格式，并按时间正序排列（老消息在前）
        const historyMessages: Message[] = chatHistories
          .map((chat) => ({
            type: (chat.messageType === 'user' ? 'user' : 'ai') as 'user' | 'ai',
            content: chat.message || '',
            createTime: chat.createTime,
          }))
          .reverse() // 反转数组，让老消息在前
        if (isLoadMore) {
          // 加载更多时，将历史消息添加到开头
          messages.value.unshift(...historyMessages)
        } else {
          // 初始加载，直接设置消息列表
          messages.value = historyMessages
        }
        // 更新游标
        lastCreateTime.value = chatHistories[chatHistories.length - 1]?.createTime
        // 检查是否还有更多历史
        hasMoreHistory.value = chatHistories.length === 10
      } else {
        hasMoreHistory.value = false
      }
      historyLoaded.value = true
    }
  } catch (error) {
    console.error('加载对话历史失败：', error)
    message.error('加载对话历史失败')
  } finally {
    loadingHistory.value = false
  }
}

// 加载更多历史消息
const loadMoreHistory = async () => {
  await loadChatHistory(true)
}

// 获取应用信息
const fetchAppInfo = async () => {
  const id = route.params.id as string
  if (!id) {
    message.error('应用ID不存在')
    router.push('/')
    return
  }

  appId.value = id

  try {
    const res = await getAppVoById({ id: id as unknown as number })
    if (res.data.code === 0 && res.data.data) {
      appInfo.value = res.data.data

      // 先加载对话历史
      await loadChatHistory()
      // 如果有至少2条对话记录，展示对应的网站
      if (messages.value.length >= 2) {
        updatePreview()
      }
      // 检查是否需要自动发送初始提示词
      // 只有在是自己的应用且没有对话历史时才自动发送
      if (
        appInfo.value.initPrompt &&
        isOwner.value &&
        messages.value.length === 0 &&
        historyLoaded.value
      ) {
        await sendInitialMessage(appInfo.value.initPrompt)
      }
    } else {
      message.error('获取应用信息失败')
      router.push('/')
    }
  } catch (error) {
    console.error('获取应用信息失败：', error)
    message.error('获取应用信息失败')
    router.push('/')
  }
}

// 发送初始消息
const sendInitialMessage = async (prompt: string) => {
  // 添加用户消息
  messages.value.push({
    type: 'user',
    content: prompt,
  })

  // 添加AI消息占位符
  const aiMessageIndex = messages.value.length
  messages.value.push({
    type: 'ai',
    content: '',
    loading: true,
  })

  await nextTick()
  scrollToBottom()

  // 开始生成
  isGenerating.value = true
  await generateCode(prompt, aiMessageIndex)
}

// 发送消息
const sendMessage = async () => {
  if (!userInput.value.trim() || isGenerating.value) {
    return
  }

  let message = userInput.value.trim()
  // 如果有选中的元素，将元素信息添加到提示词中
  if (selectedElementInfo.value) {
    let elementContext = `\n\n选中元素信息：`
    if (selectedElementInfo.value.pagePath) {
      elementContext += `\n- 页面路径: ${selectedElementInfo.value.pagePath}`
    }
    elementContext += `\n- 标签: ${selectedElementInfo.value.tagName.toLowerCase()}\n- 选择器: ${selectedElementInfo.value.selector}`
    if (selectedElementInfo.value.textContent) {
      elementContext += `\n- 当前内容: ${selectedElementInfo.value.textContent.substring(0, 100)}`
    }
    message += elementContext
  }
  userInput.value = ''
  // 添加用户消息（包含元素信息）
  messages.value.push({
    type: 'user',
    content: message,
  })

  // 发送消息后，清除选中元素并退出编辑模式
  if (selectedElementInfo.value) {
    clearSelectedElement()
    if (isEditMode.value) {
      toggleEditMode()
    }
  }

  // 添加AI消息占位符
  const aiMessageIndex = messages.value.length
  messages.value.push({
    type: 'ai',
    content: '',
    loading: true,
  })

  await nextTick()
  scrollToBottom()

  // 开始生成
  isGenerating.value = true
  await generateCode(message, aiMessageIndex)
}

// 生成代码 - 使用 EventSource 处理流式响应
const generateCode = async (userMessage: string, aiMessageIndex: number) => {
  let eventSource: EventSource | null = null
  let streamCompleted = false

  try {
    // 获取 axios 配置的 baseURL
    const baseURL = request.defaults.baseURL || API_BASE_URL

    // 构建URL参数
    const params = new URLSearchParams({
      appId: appId.value || '',
      message: userMessage,
    })

    const url = `${baseURL}/app/chat/gen/code?${params}`

    // 创建 EventSource 连接
    eventSource = new EventSource(url, {
      withCredentials: true,
    })

    let fullContent = ''

    // 处理接收到的消息
    eventSource.onmessage = function (event) {
      if (streamCompleted) return

      try {
        // 解析JSON包装的数据
        const parsed = JSON.parse(event.data)
        const content = parsed.d

        // 拼接内容
        if (content !== undefined && content !== null) {
          fullContent += content
          messages.value[aiMessageIndex].content = fullContent
          messages.value[aiMessageIndex].loading = false
          scrollToBottom()
        }
      } catch (error) {
        console.error('解析消息失败:', error)
        handleError(error, aiMessageIndex)
      }
    }

    // 处理done事件
    eventSource.addEventListener('done', function () {
      if (streamCompleted) return

      streamCompleted = true
      isGenerating.value = false
      eventSource?.close()

      // 延迟更新预览，确保后端已完成处理
      setTimeout(async () => {
        await fetchAppInfo()
        updatePreview()
      }, 1000)
    })

    // 处理business-error事件（后端限流等错误）
    eventSource.addEventListener('business-error', function (event: MessageEvent) {
      if (streamCompleted) return

      try {
        const errorData = JSON.parse(event.data)
        console.error('SSE业务错误事件:', errorData)

        // 显示具体的错误信息
        const errorMessage = errorData.message || '生成过程中出现错误'
        messages.value[aiMessageIndex].content = `❌ ${errorMessage}`
        messages.value[aiMessageIndex].loading = false
        message.error(errorMessage)

        streamCompleted = true
        isGenerating.value = false
        eventSource?.close()
      } catch (parseError) {
        console.error('解析错误事件失败:', parseError, '原始数据:', event.data)
        handleError(new Error('服务器返回错误'), aiMessageIndex)
      }
    })

    // 处理错误
    eventSource.onerror = function () {
      if (streamCompleted || !isGenerating.value) return
      // 检查是否是正常的连接关闭
      if (eventSource?.readyState === EventSource.CONNECTING) {
        streamCompleted = true
        isGenerating.value = false
        eventSource?.close()

        setTimeout(async () => {
          await fetchAppInfo()
          updatePreview()
        }, 1000)
      } else {
        handleError(new Error('SSE连接错误'), aiMessageIndex)
      }
    }
  } catch (error) {
    console.error('创建 EventSource 失败：', error)
    handleError(error, aiMessageIndex)
  }
}

// 错误处理函数
const handleError = (error: unknown, aiMessageIndex: number) => {
  console.error('生成代码失败：', error)
  messages.value[aiMessageIndex].content = '抱歉，生成过程中出现了错误，请重试。'
  messages.value[aiMessageIndex].loading = false
  message.error('生成失败，请重试')
  isGenerating.value = false
}

// 更新预览
const updatePreview = () => {
  if (appId.value) {
    const codegenType = appInfo.value?.codegenType || CodeGenTypeEnum.HTML
    const newPreviewUrl = getStaticPreviewUrl(codegenType, appId.value)
    previewUrl.value = newPreviewUrl
    previewReady.value = true
  }
}

// 滚动到底部
const scrollToBottom = () => {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
  }
}

// 下载代码
const downloadCode = async () => {
  if (!appId.value) {
    message.error('应用ID不存在')
    return
  }
  downloading.value = true
  try {
    const API_BASE_URL = request.defaults.baseURL || ''
    const url = `${API_BASE_URL}/app/download/${appId.value}`
    const response = await fetch(url, {
      method: 'GET',
      credentials: 'include',
    })
    if (!response.ok) {
      throw new Error(`下载失败: ${response.status}`)
    }
    // 获取文件名
    const contentDisposition = response.headers.get('Content-Disposition')
    const fileName = contentDisposition?.match(/filename="(.+)"/)?.[1] || `app-${appId.value}.zip`
    // 下载文件
    const blob = await response.blob()
    const downloadUrl = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = downloadUrl
    link.download = fileName
    link.click()
    // 清理
    URL.revokeObjectURL(downloadUrl)
    message.success('代码下载成功')
  } catch (error) {
    console.error('下载失败：', error)
    message.error('下载失败，请重试')
  } finally {
    downloading.value = false
  }
}

// 部署应用
const deployApp = async () => {
  if (!appId.value) {
    message.error('应用ID不存在')
    return
  }

  deploying.value = true
  try {
    const res = await deployAppApi({
      appId: appId.value as unknown as number,
    })

    if (res.data.code === 0 && res.data.data) {
      deployUrl.value = res.data.data
      deployModalVisible.value = true
      message.success('部署成功')
    } else {
      message.error('部署失败：' + res.data.message)
    }
  } catch (error) {
    console.error('部署失败：', error)
    message.error('部署失败，请重试')
  } finally {
    deploying.value = false
  }
}

// 在新窗口打开预览
const openInNewTab = () => {
  if (previewUrl.value) {
    window.open(previewUrl.value, '_blank')
  }
}

// 打开部署的网站
const openDeployedSite = () => {
  if (deployUrl.value) {
    window.open(deployUrl.value, '_blank')
  }
}

// iframe加载完成
const onIframeLoad = () => {
  previewReady.value = true
  const iframe = document.querySelector('.preview-iframe') as HTMLIFrameElement
  if (iframe) {
    visualEditor.init(iframe)
    visualEditor.onIframeLoad()
  }
}

// 编辑应用
const editApp = () => {
  if (appInfo.value?.id) {
    router.push(`/app/edit/${appInfo.value.id}`)
  }
}

// 删除应用
const deleteApp = async () => {
  if (!appInfo.value?.id) return

  try {
    const res = await deleteAppApi({ id: appInfo.value.id })
    if (res.data.code === 0) {
      message.success('删除成功')
      appDetailVisible.value = false
      router.push('/')
    } else {
      message.error('删除失败：' + res.data.message)
    }
  } catch (error) {
    console.error('删除失败：', error)
    message.error('删除失败')
  }
}

// 可视化编辑相关函数
const toggleEditMode = () => {
  // 检查 iframe 是否已经加载
  const iframe = document.querySelector('.preview-iframe') as HTMLIFrameElement
  if (!iframe) {
    message.warning('请等待页面加载完成')
    return
  }
  // 确保 visualEditor 已初始化
  if (!previewReady.value) {
    message.warning('请等待页面加载完成')
    return
  }
  const newEditMode = visualEditor.toggleEditMode()
  isEditMode.value = newEditMode
}

const clearSelectedElement = () => {
  selectedElementInfo.value = null
  visualEditor.clearSelection()
}

const getInputPlaceholder = () => {
  if (selectedElementInfo.value) {
    return `正在编辑 ${selectedElementInfo.value.tagName.toLowerCase()} 元素，描述您想要的修改...`
  }
  return '请描述你想生成的网站，越详细效果越好哦'
}

// 页面加载时获取应用信息
onMounted(() => {
  fetchAppInfo()

  // 监听 iframe 消息
  window.addEventListener('message', (event) => {
    visualEditor.handleIframeMessage(event)
  })
})

// 清理资源
onUnmounted(() => {
  // EventSource 会在组件卸载时自动清理
})
</script>

<style scoped>
#appChatPage {
  height: 100vh;
  display: flex;
  flex-direction: column;
  padding: 16px;
  background: #fdfdfd;
}

/* 顶部栏 */
.header-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}

.code-gen-type-tag {
  font-size: 12px;
}

.app-name {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1a1a1a;
}

.header-right {
  display: flex;
  gap: 12px;
}

/* 主要内容区域 */
.main-content {
  flex: 1;
  display: flex;
  gap: 16px;
  padding: 8px;
  overflow: hidden;
}

/* 左侧对话区域 */
.chat-section {
  flex: 2;
  display: flex;
  flex-direction: column;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.messages-container {
  flex: 0.9;
  padding: 16px;
  overflow-y: auto;
  scroll-behavior: smooth;
}

.message-item {
  margin-bottom: 12px;
}

.user-message {
  display: flex;
  justify-content: flex-end;
  align-items: flex-start;
  gap: 8px;
}

.ai-message {
  display: flex;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
}

.message-content {
  max-width: 70%;
  padding: 12px 16px;
  border-radius: 12px;
  line-height: 1.5;
  word-wrap: break-word;
}

.user-message .message-content {
  background: #1890ff;
  color: white;
}

.ai-message .message-content {
  background: #f5f5f5;
  color: #1a1a1a;
  padding: 8px 12px;
}

.message-avatar {
  flex-shrink: 0;
}

.loading-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #666;
}

/* 加载更多按钮 */
.load-more-container {
  text-align: center;
  padding: 8px 0;
  margin-bottom: 16px;
}

/* 输入区域 */
.input-container {
  padding: 16px;
  background: white;
}

.input-wrapper {
  position: relative;
}

.input-wrapper .ant-input {
  padding-right: 50px;
}

.input-actions {
  position: absolute;
  bottom: 8px;
  right: 8px;
}

/* 右侧预览区域 */
.preview-section {
  flex: 3;
  display: flex;
  flex-direction: column;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.preview-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  border-bottom: 1px solid #e8e8e8;
}

.preview-header h3 {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}

.preview-actions {
  display: flex;
  gap: 8px;
}

.preview-content {
  flex: 1;
  position: relative;
  overflow: hidden;
}

.preview-placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #666;
}

.placeholder-icon {
  font-size: 48px;
  margin-bottom: 16px;
}

.preview-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #666;
}

.preview-loading p {
  margin-top: 16px;
}

.preview-iframe {
  width: 100%;
  height: 100%;
  border: none;
}

.selected-element-alert {
  margin: 0 16px;
}

/* 响应式设计 */
@media (max-width: 1024px) {
  .main-content {
    flex-direction: column;
  }

  .chat-section,
  .preview-section {
    flex: none;
    height: 50vh;
  }
}

@media (max-width: 768px) {
  .header-bar {
    padding: 12px 16px;
  }

  .app-name {
    font-size: 16px;
  }

  .main-content {
    padding: 8px;
    gap: 8px;
  }

  .message-content {
    max-width: 85%;
  }

  /* 选中元素信息样式 */
  .selected-element-alert {
    margin: 0 16px;
  }

  .selected-element-info {
    line-height: 1.4;
  }

  .element-header {
    margin-bottom: 8px;
  }

  .element-details {
    margin-top: 8px;
  }

  .element-item {
    margin-bottom: 4px;
    font-size: 13px;
  }

  .element-item:last-child {
    margin-bottom: 0;
  }

  .element-tag {
    font-family: 'Monaco', 'Menlo', monospace;
    font-size: 14px;
    font-weight: 600;
    color: #007bff;
  }

  .element-id {
    color: #28a745;
    margin-left: 4px;
  }

  .element-class {
    color: #ffc107;
    margin-left: 4px;
  }

  .element-selector-code {
    font-family: 'Monaco', 'Menlo', monospace;
    background: #f6f8fa;
    padding: 2px 4px;
    border-radius: 3px;
    font-size: 12px;
    color: #d73a49;
    border: 1px solid #e1e4e8;
  }

  /* 编辑模式按钮样式 */
  .edit-mode-active {
    background-color: #52c41a !important;
    border-color: #52c41a !important;
    color: white !important;
  }

  .edit-mode-active:hover {
    background-color: #73d13d !important;
    border-color: #73d13d !important;
  }
}
</style>
