// react-fe/src/pages/app/AppEditPage.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router'
import { toast } from 'sonner'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Skeleton } from '@/components/ui/skeleton'
import UserInfo from '@/components/UserInfo'
import { useUserStore } from '@/stores/userStore'
import { getAppVoById, updateApp, updateAppByAdmin } from '@/api/appController'
import { formatCodeGenType } from '@/utils/codeGenTypes'
import { formatTime } from '@/utils/time'
import { getStaticPreviewUrl } from '@/config/env'

const formSchema = z.object({
  appName: z
    .string()
    .min(1, 'Please enter app name')
    .max(50, 'App name should be 1-50 characters'),
  cover: z.string().url('Please enter a valid URL').or(z.literal('')).optional(),
  priority: z.number().min(0, 'Priority range is 0-99').max(99, 'Priority range is 0-99').optional(),
})

type FormValues = z.infer<typeof formSchema>

export default function AppEditPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { loginUser } = useUserStore()

  const [appInfo, setAppInfo] = useState<API.AppVO>()
  const [loading, setLoading] = useState(false)
  const [submitting, setSubmitting] = useState(false)

  const isAdmin = loginUser.userRole === 'admin'

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      appName: '',
      cover: '',
      priority: 0,
    },
  })

  // Fetch app info
  const fetchAppInfo = async () => {
    if (!id) {
      toast.error('App ID does not exist')
      navigate('/')
      return
    }

    setLoading(true)
    try {
      const res = await getAppVoById({ id: Number(id) })
      if (res.data.code === 0 && res.data.data) {
        const app = res.data.data
        setAppInfo(app)

        // Check permission
        if (!isAdmin && app.userId !== loginUser.id) {
          toast.error('You do not have permission to edit this app')
          navigate('/')
          return
        }

        // Fill form data
        form.reset({
          appName: app.appName || '',
          cover: app.cover || '',
          priority: app.priority || 0,
        })
      } else {
        toast.error('Failed to get app info')
        navigate('/')
      }
    } catch (error) {
      console.error('Failed to get app info:', error)
      toast.error('Failed to get app info')
      navigate('/')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchAppInfo()
  }, [id])

  // Submit form
  const onSubmit = async (data: FormValues) => {
    if (!appInfo?.id) return

    setSubmitting(true)
    try {
      let res
      if (isAdmin) {
        res = await updateAppByAdmin({
          id: appInfo.id,
          appName: data.appName,
          cover: data.cover,
          priority: data.priority,
        })
      } else {
        res = await updateApp({
          id: appInfo.id,
          appName: data.appName,
        })
      }

      if (res.data.code === 0) {
        toast.success('Update successful')
        await fetchAppInfo()
      } else {
        toast.error('Update failed: ' + res.data.message)
      }
    } catch (error) {
      console.error('Update failed:', error)
      toast.error('Update failed')
    } finally {
      setSubmitting(false)
    }
  }

  // Reset form
  const resetForm = () => {
    if (appInfo) {
      form.reset({
        appName: appInfo.appName || '',
        cover: appInfo.cover || '',
        priority: appInfo.priority || 0,
      })
    }
  }

  // Go to chat page
  const goToChat = () => {
    if (appInfo?.id) {
      navigate(`/app/chat/${appInfo.id}`)
    }
  }

  // Open preview
  const openPreview = () => {
    if (appInfo?.codeGenType && appInfo?.id) {
      const url = getStaticPreviewUrl(appInfo.codeGenType, String(appInfo.id))
      window.open(url, '_blank')
    }
  }

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Edit App Info</h1>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Basic Info</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-4">
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-10 w-full" />
              <Skeleton className="h-24 w-full" />
            </div>
          ) : (
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                <FormField
                  control={form.control}
                  name="appName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>App Name</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter app name"
                          maxLength={50}
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {isAdmin && (
                  <>
                    <FormField
                      control={form.control}
                      name="cover"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>App Cover</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="Enter cover image URL"
                              {...field}
                            />
                          </FormControl>
                          <FormDescription>
                            Supports image links, recommended size: 400x300
                          </FormDescription>
                          {field.value && (
                            <div className="mt-3 p-3 border rounded-lg bg-gray-50">
                              <img
                                src={field.value}
                                alt="Cover preview"
                                className="max-w-[200px] h-auto rounded"
                                onError={(e) => {
                                  (e.target as HTMLImageElement).style.display = 'none'
                                }}
                              />
                            </div>
                          )}
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="priority"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Priority</FormLabel>
                          <FormControl>
                            <Input
                              type="number"
                              min={0}
                              max={99}
                              className="w-[200px]"
                              value={field.value ?? 0}
                              onChange={(e) => field.onChange(Number(e.target.value) || 0)}
                              onBlur={field.onBlur}
                              name={field.name}
                              ref={field.ref}
                            />
                          </FormControl>
                          <FormDescription>
                            Set to 99 for featured app
                          </FormDescription>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </>
                )}

                <div>
                  <FormLabel>Initial Prompt</FormLabel>
                  <Textarea
                    value={appInfo?.initPrompt || ''}
                    placeholder="Initial prompt"
                    rows={4}
                    maxLength={1000}
                    disabled
                    className="mt-2"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Initial prompt cannot be modified
                  </p>
                </div>

                <div>
                  <FormLabel>Generation Type</FormLabel>
                  <Input
                    value={formatCodeGenType(appInfo?.codeGenType || '')}
                    placeholder="Generation type"
                    disabled
                    className="mt-2"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Generation type cannot be modified
                  </p>
                </div>

                {appInfo?.deployKey && (
                  <div>
                    <FormLabel>Deploy Key</FormLabel>
                    <Input
                      value={appInfo.deployKey}
                      placeholder="Deploy key"
                      disabled
                      className="mt-2"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Deploy key cannot be modified
                    </p>
                  </div>
                )}

                <div className="flex gap-3 pt-4">
                  <Button type="submit" disabled={submitting}>
                    {submitting ? 'Saving...' : 'Save Changes'}
                  </Button>
                  <Button type="button" variant="outline" onClick={resetForm}>
                    Reset
                  </Button>
                  <Button type="button" variant="link" onClick={goToChat}>
                    Go to Chat
                  </Button>
                </div>
              </form>
            </Form>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>App Info</CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-4">
              <Skeleton className="h-6 w-full" />
              <Skeleton className="h-6 w-full" />
              <Skeleton className="h-6 w-full" />
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-4">
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">App ID</div>
                <div className="font-medium">{appInfo?.id}</div>
              </div>
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">Creator</div>
                <UserInfo user={appInfo?.user} size="sm" />
              </div>
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">Created At</div>
                <div className="font-medium">{formatTime(appInfo?.createTime)}</div>
              </div>
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">Updated At</div>
                <div className="font-medium">{formatTime(appInfo?.updateTime)}</div>
              </div>
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">Deployed At</div>
                <div className="font-medium">
                  {appInfo?.deployedTime ? formatTime(appInfo.deployedTime) : 'Not deployed'}
                </div>
              </div>
              <div className="border rounded p-3">
                <div className="text-sm text-gray-500 mb-1">Preview Link</div>
                {appInfo?.deployKey ? (
                  <Button variant="link" size="sm" className="p-0 h-auto" onClick={openPreview}>
                    View Preview
                  </Button>
                ) : (
                  <span className="text-gray-400">Not deployed</span>
                )}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

// yu-ai-code-mother-frontend/src/pages/app/AppEditPage.vue
<template>
  <div id="appEditPage">
    <div class="page-header">
      <h1>编辑应用信息</h1>
    </div>

    <div class="edit-container">
      <a-card title="基本信息" :loading="loading">
        <a-form
          :model="formData"
          :rules="rules"
          layout="vertical"
          @finish="handleSubmit"
          ref="formRef"
        >
          <a-form-item label="应用名称" name="appName">
            <a-input
              v-model:value="formData.appName"
              placeholder="请输入应用名称"
              :maxlength="50"
              show-count
            />
          </a-form-item>

          <a-form-item
            v-if="isAdmin"
            label="应用封面"
            name="cover"
            extra="支持图片链接，建议尺寸：400x300"
          >
            <a-input v-model:value="formData.cover" placeholder="请输入封面图片链接" />
            <div v-if="formData.cover" class="cover-preview">
              <a-image
                :src="formData.cover"
                :width="200"
                :height="150"
                fallback="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
              />
            </div>
          </a-form-item>

          <a-form-item v-if="isAdmin" label="优先级" name="priority" extra="设置为99表示精选应用">
            <a-input-number
              v-model:value="formData.priority"
              :min="0"
              :max="99"
              style="width: 200px"
            />
          </a-form-item>

          <a-form-item label="初始提示词" name="initPrompt">
            <a-textarea
              v-model:value="formData.initPrompt"
              placeholder="请输入初始提示词"
              :rows="4"
              :maxlength="1000"
              show-count
              disabled
            />
            <div class="form-tip">初始提示词不可修改</div>
          </a-form-item>

          <a-form-item label="生成类型" name="codegenType">
            <a-input
              :value="formatCodeGenType(formData.codegenType)"
              placeholder="生成类型"
              disabled
            />
            <div class="form-tip">生成类型不可修改</div>
          </a-form-item>

          <a-form-item v-if="formData.deployKey" label="部署密钥" name="deployKey">
            <a-input v-model:value="formData.deployKey" placeholder="部署密钥" disabled />
            <div class="form-tip">部署密钥不可修改</div>
          </a-form-item>

          <a-form-item>
            <a-space>
              <a-button type="primary" html-type="submit" :loading="submitting">
                保存修改
              </a-button>
              <a-button @click="resetForm">重置</a-button>
              <a-button type="link" @click="goToChat">进入对话</a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </a-card>

      <!-- 应用信息展示 -->
      <a-card title="应用信息" style="margin-top: 24px">
        <a-descriptions :column="2" bordered>
          <a-descriptions-item label="应用ID">
            {{ appInfo?.id }}
          </a-descriptions-item>
          <a-descriptions-item label="创建者">
            <UserInfo :user="appInfo?.user" size="small" />
          </a-descriptions-item>
          <a-descriptions-item label="创建时间">
            {{ formatTime(appInfo?.createTime) }}
          </a-descriptions-item>
          <a-descriptions-item label="更新时间">
            {{ formatTime(appInfo?.updateTime) }}
          </a-descriptions-item>
          <a-descriptions-item label="部署时间">
            {{ appInfo?.deployTime ? formatTime(appInfo.deployTime) : '未部署' }}
          </a-descriptions-item>
          <a-descriptions-item label="访问链接">
            <a-button v-if="appInfo?.deployKey" type="link" @click="openPreview" size="small">
              查看预览
            </a-button>
            <span v-else>未部署</span>
          </a-descriptions-item>
        </a-descriptions>
      </a-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { useLoginUserStore } from '@/stores/loginUser'
import { getAppVoById, updateApp, updateAppByAdmin } from '@/api/appController'
import { formatCodeGenType } from '@/utils/codeGenTypes'
import { formatTime } from '@/utils/time'
import UserInfo from '@/components/UserInfo.vue'
import { getStaticPreviewUrl } from '@/config/env'
import type { FormInstance } from 'ant-design-vue'

const route = useRoute()
const router = useRouter()
const loginUserStore = useLoginUserStore()

// 应用信息
const appInfo = ref<API.AppVO>()
const loading = ref(false)
const submitting = ref(false)
const formRef = ref<FormInstance>()

// 表单数据
const formData = reactive({
  appName: '',
  cover: '',
  priority: 0,
  initPrompt: '',
  codegenType: '',
  deployKey: '',
})

// 是否为管理员
const isAdmin = computed(() => {
  return loginUserStore.loginUser.userRole === 'admin'
})

// 表单验证规则
const rules = {
  appName: [
    { required: true, message: '请输入应用名称', trigger: 'blur' },
    { min: 1, max: 50, message: '应用名称长度在1-50个字符', trigger: 'blur' },
  ],
  cover: [{ type: 'url', message: '请输入有效的URL', trigger: 'blur' }],
  priority: [{ type: 'number', min: 0, max: 99, message: '优先级范围0-99', trigger: 'blur' }],
}

// 获取应用信息
const fetchAppInfo = async () => {
  const id = route.params.id as string
  if (!id) {
    message.error('应用ID不存在')
    router.push('/')
    return
  }

  loading.value = true
  try {
    const res = await getAppVoById({ id: id as unknown as number })
    if (res.data.code === 0 && res.data.data) {
      appInfo.value = res.data.data

      // 检查权限
      if (!isAdmin.value && appInfo.value.userId !== loginUserStore.loginUser.id) {
        message.error('您没有权限编辑此应用')
        router.push('/')
        return
      }

      // 填充表单数据
      formData.appName = appInfo.value.appName || ''
      formData.cover = appInfo.value.cover || ''
      formData.priority = appInfo.value.priority || 0
      formData.initPrompt = appInfo.value.initPrompt || ''
      formData.codegenType = appInfo.value.codegenType || ''
      formData.deployKey = appInfo.value.deployKey || ''
    } else {
      message.error('获取应用信息失败')
      router.push('/')
    }
  } catch (error) {
    console.error('获取应用信息失败：', error)
    message.error('获取应用信息失败')
    router.push('/')
  } finally {
    loading.value = false
  }
}

// 提交表单
const handleSubmit = async () => {
  if (!appInfo.value?.id) return

  submitting.value = true
  try {
    let res
    if (isAdmin.value) {
      // 管理员可以修改更多字段
      res = await updateAppByAdmin({
        id: appInfo.value.id,
        appName: formData.appName,
        cover: formData.cover,
        priority: formData.priority,
      })
    } else {
      // 普通用户只能修改应用名称
      res = await updateApp({
        id: appInfo.value.id,
        appName: formData.appName,
      })
    }

    if (res.data.code === 0) {
      message.success('修改成功')
      // 重新获取应用信息
      await fetchAppInfo()
    } else {
      message.error('修改失败：' + res.data.message)
    }
  } catch (error) {
    console.error('修改失败：', error)
    message.error('修改失败')
  } finally {
    submitting.value = false
  }
}

// 重置表单
const resetForm = () => {
  if (appInfo.value) {
    formData.appName = appInfo.value.appName || ''
    formData.cover = appInfo.value.cover || ''
    formData.priority = appInfo.value.priority || 0
  }
  formRef.value?.clearValidate()
}

// 进入对话页面
const goToChat = () => {
  if (appInfo.value?.id) {
    router.push(`/app/chat/${appInfo.value.id}`)
  }
}

// 打开预览
const openPreview = () => {
  if (appInfo.value?.codegenType && appInfo.value?.id) {
    const url = getStaticPreviewUrl(appInfo.value.codegenType, String(appInfo.value.id))
    window.open(url, '_blank')
  }
}

// 页面加载时获取应用信息
onMounted(() => {
  fetchAppInfo()
})
</script>

<style scoped>
#appEditPage {
  padding: 24px;
  max-width: 1000px;
  margin: 0 auto;
}

.page-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 24px;
}

.page-header h1 {
  margin: 0;
  font-size: 24px;
  font-weight: 600;
}

.edit-container {
  border-radius: 8px;
}

.cover-preview {
  margin-top: 12px;
  padding: 12px;
  border: 1px solid #e8e8e8;
  border-radius: 6px;
  background: #fafafa;
}

.form-tip {
  font-size: 12px;
  color: #999;
  margin-top: 4px;
}

:deep(.ant-card-head) {
  background: #fafafa;
}

:deep(.ant-descriptions-item-label) {
  background: #fafafa;
  font-weight: 500;
}
</style>
